
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      PORT: 4000
      MONGODB_URI: mongodb://mongodb:27017/mydatabase
    ports:
      - 4000:3000
    depends_on:
      mongodb:
        condition: service_healthy
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
    - mongodata:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - node-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword

  app:
    image: liamtgood/cmpsc421lab-server:latest
    depends_on:
      - mongodb
    ports:
     - 8080:3000
    networks:
      - node-network
    environment:
      DATABASE_URL: mongodb://root:examplepassword@mongodb:27017/mydatabase
    

volumes:
  mongodata:
    driver: local
networks:
  node-network:
    driver: bridge

